services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: db_users
      MYSQL_ROOT_PASSWORD: kathem_00x
    ports:
      - "3307:3306"
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "./wait-for-it.sh db:3306 -- 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"