services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: db_users
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
  web:
    secrets:
      - django_secret_key
    environment:
      DJANGO_SECRET_KEY: /run/secrets/django_secret_key
      DEBUG: "1"
      DB_NAME: db_users
      DB_USER: root
      DB_PASSWORD: dbpassword
      DB_HOST: db
      DB_PORT: 5432
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

secrets:
  django_secret_key:
    file: ./django_secret_key.txt
